CREATE TABLE usuario(
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    cpf VARCHAR(20) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    perfil VARCHAR(20) NOT NULL
);